In [1]:
 import numpy

In [2]:
numpy.array([1,2,3])

array([1, 2, 3])

In [7]:
import numpy as np
a=np.array([1,2,3,4])
print(a)

print("#")
b=np.array([[1,2,3],[2,3,5]])
print(b)

[1 2 3 4]
#
[[1 2 3]
 [2 3 5]]


In [9]:
b.shape

(2, 3)

In [10]:
a.shape

(4,)

In [11]:
  b.dtype

dtype('int32')

In [12]:
b.ndim

2

In [13]:
print(type(a))

<class 'numpy.ndarray'>


In [18]:
np.arange(10)               #automatically create the array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
c=range(10000)

In [21]:
%timeit [i**3 for i in c]

5.16 ms ± 397 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [22]:
c_numpy=np.arange(10000)
%timeit c_numpy**3

22.7 µs ± 296 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [23]:
np.full((3,3),2)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [24]:
np.full((4,4),5.5)

array([[5.5, 5.5, 5.5, 5.5],
       [5.5, 5.5, 5.5, 5.5],
       [5.5, 5.5, 5.5, 5.5],
       [5.5, 5.5, 5.5, 5.5]])

In [25]:
np.full((4,4),5.5 ,dtype=np.int)           #cutting all the integer part aside

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [27]:
 #diagonal ndarray

np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [28]:
v=np.array([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

In [31]:
np.tile(v,(3,1))

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [33]:
np.tile(v,(3,2))            #adds up column

array([[1, 2, 3, 4, 5, 1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5, 1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]])

In [37]:
np.random.random()

0.015533890537358985

In [41]:
#between 1 to 50 slpit the data in 100 parts and return it
a=np.linspace(1,50,100)

In [42]:
a


array([ 1.        ,  1.49494949,  1.98989899,  2.48484848,  2.97979798,
        3.47474747,  3.96969697,  4.46464646,  4.95959596,  5.45454545,
        5.94949495,  6.44444444,  6.93939394,  7.43434343,  7.92929293,
        8.42424242,  8.91919192,  9.41414141,  9.90909091, 10.4040404 ,
       10.8989899 , 11.39393939, 11.88888889, 12.38383838, 12.87878788,
       13.37373737, 13.86868687, 14.36363636, 14.85858586, 15.35353535,
       15.84848485, 16.34343434, 16.83838384, 17.33333333, 17.82828283,
       18.32323232, 18.81818182, 19.31313131, 19.80808081, 20.3030303 ,
       20.7979798 , 21.29292929, 21.78787879, 22.28282828, 22.77777778,
       23.27272727, 23.76767677, 24.26262626, 24.75757576, 25.25252525,
       25.74747475, 26.24242424, 26.73737374, 27.23232323, 27.72727273,
       28.22222222, 28.71717172, 29.21212121, 29.70707071, 30.2020202 ,
       30.6969697 , 31.19191919, 31.68686869, 32.18181818, 32.67676768,
       33.17171717, 33.66666667, 34.16161616, 34.65656566, 35.15

In [43]:
#memory used in bytes
a.itemsize

8

In [44]:
np.arange(18).shape

(18,)

In [49]:
b=np.arange(18).reshape(2,3,3)
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [50]:
np.arange(18).reshape(2,3,-1)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [53]:
a=np.array([2,3,4,5,6,7,8,9])
a

array([2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
#want 6 10 14 as output so we have to use bundle list

#a[2,3,6] => error too many indices for array
a[[2,3,6]]

array([4, 5, 8])

In [67]:
# *in numpy array if one assign array to another array it will still point to original location

a=np.arange(10)

In [68]:
b= 

In [72]:
a


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
b[0]=11

In [75]:
b

array([11,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [76]:
a

array([11,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [85]:
 #hahahaha! :) so use copy function
x=np.arange(10)
y=x.copy()
y[0] = 99
y

array([99,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [86]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
a=np.array([[1,2,3,4],[5,6,7]])

In [102]:
a

array([list([1, 2, 3, 4]), list([5, 6, 7])], dtype=object)

In [104]:
#note the diffrence
a=np.array([[1,2,3],[5,6,7]])
a

array([[1, 2, 3],
       [5, 6, 7]])

In [105]:
a.T

array([[1, 5],
       [2, 6],
       [3, 7]])

In [106]:
b=np.array([[7,8,9],[4,5,7]])

In [107]:
b

array([[7, 8, 9],
       [4, 5, 7]])

In [109]:
#now vertically stack these elements
np.vstack((a,b))

array([[1, 2, 3],
       [5, 6, 7],
       [7, 8, 9],
       [4, 5, 7]])

In [110]:
#horizontal stack
np.hstack((a,b))

array([[1, 2, 3, 7, 8, 9],
       [5, 6, 7, 4, 5, 7]])

In [112]:
a=np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [116]:
#dot product
b=np.arange(1,10).reshape(3,3)
np.dot(a,b)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [117]:
a=np.array([1,1,0],dtype=bool)
b=np.array([1,0,1],dtype=bool)